### ISSUE TITLE
Bump to 9.4.0-4 to address permission issues

### ISSUE THREAD

**Issue by lance** [bucharest-gold/centos7-s2i-nodejs#40]
## New Node.js minor version bump

Use this issue template to report a minor version bump in Node.js.

New Node.js version number: 9.4.0-4

### Tasks

Check out the branch for whatever version is being updated. E.g.

```
git checkout v9.x
```

All of the following tasks occur on this branch.

- [x] Ensure a [published node-rpm](https://github.com/bucharest-gold/node-rpm/releases) for this version exists.
- [ ] Update versions.mk with the correct version number for `NODE_VERSION` and `NPM_VERSION` **(not relevant)**.
- [ ] Update releases.json and image-streams.centos7.json with new version information. **(not relevant)**.

```
node-metadata -i <major-version> | jq '.' > releases.json
node-image-stream -f releases.json -i bucharestgold/centos7-s2i-nodejs > image-streams.centos7.json
```

- [x] Ensure that `make all` passes successfully.
- [x] Tag the new release: `git tag -s -m 'Update to Node.js version 8.10.0' v8.10.0`
- [x] Publish the release to docker hub (you will need to have `DOCKER_USER` and `DOCKER_PASS` in your environment).

```
make tag publish
```

- [x] Finally, push your changes to github: `git push origin <branch> --follow-tags`.

Fixes: https://github.com/bucharest-gold/centos7-s2i-nodejs/issues/38

**Comment by lance** [comment]
Closed with tag `node-9.4.0-6`.
